# Generated by Django 3.2 on 2021-05-18 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secure_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('path', models.FileField(upload_to='secure-files/%Y/%m/%d', verbose_name='文件路径')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '安全文件',
                'verbose_name_plural': '安全文件',
                'permissions': (('view_securefile', '下载文件'),),
                'default_permissions': (),
            },
            bases=(secure_file.models.FileFromPathMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InSecureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('path', models.FileField(upload_to='insecure-files/%Y/%m/%d', verbose_name='文件路径')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '不安全文件',
                'verbose_name_plural': '不安全文件',
                'default_permissions': (),
            },
            bases=(secure_file.models.FileFromPathMixin, models.Model),
        ),
    ]
